### ISSUE TITLE
Switch from c++

### ISSUE THREAD

**Issue by mdm508** [sourTaste000/dos#1]
Alex, I was thinking we could maybe try out a new programming language that might be better for you in the long run.

If your up for that, I will prepare a special lesson for you on Saturday.

https://htdp.org/2019-02-24/

Please read the prologue.

download program enviorment here

https://download.racket-lang.org

**Comment by sourTaste000** [comment]
okay

**Comment by sourTaste000** [comment]
but when and how

**Comment by sourTaste000** [comment]
can you email me?
